### ISSUE TITLE
AzureVault should not hard-code the DNS endpoint

### ISSUE THREAD

**Issue by matgnt** [eclipse-edc/Technology-Azure#16]
Currently the Azure Vault hard codes the DNS endpoint and does not allow to set this in the configuration of the connector. This makes it impossible to black-box test a connector image

```
.vaultUrl("https://" + keyVaultName + ".vault.azure.net")
```
[                .vaultUrl("https://" + keyVaultName + ".vault.azure.net")](https://github.com/eclipse-edc/Connector/blob/63a73ec4b585253727a5c56cf9a7e51045747dee/extensions/common/vault/vault-azure/src/main/java/org/eclipse/edc/vault/azure/AzureVault.java#L146)

The request is to change this to something similar as it is in HashicorpVault:

https://github.com/eclipse-edc/Connector/blob/63a73ec4b585253727a5c56cf9a7e51045747dee/extensions/common/vault/vault-hashicorp/src/main/java/org/eclipse/edc/vault/hashicorp/HashicorpVaultExtension.java#L38

that allows to change the entire endpoint.

Any thoughts on this?

---
Matthias Binzer

**Comment by matgnt** [comment]
I think this is still relevant. Can it please be be re-opened again?

**Comment by SebastianOpriel** [comment]
agree, this is still a problem. We should re-open the issue. We would be happy to contribute the necessary adjustment.

**Comment by ndr-brt** [comment]
@SebastianOpriel is there someone that can be assigned to this? if so I will assign and re-open

**Comment by ununhexium** [comment]
@ndr-brt 
I will start working on this.

**Comment by matgnt** [comment]
Thanks @SebastianOpriel  and @ununhexium for this!!!
