### ISSUE TITLE
Inconsistent authentication strategy when transferring several files

### ISSUE THREAD

**Issue by zub4t** [eclipse-edc/Technology-Azure#168]
# Bug Report

## Describe the Bug
When the transfer request needs to handle several files, it does not use `sharedKey` to list all the files of a specific prefix, even when it does exist. The method expects the credentials to be stored with a hard-coded pattern key that might not correspond to the value in `keyName`.

### Expected Behavior
All authentication strategies need to be consistent, this implies that [`listContainerFolder`](https://github.com/eclipse-edc/Technology-Azure/blob/fdbc521750959868cf1ff6c93230e6220ba8ab70/extensions/common/azure/azure-blob-core/src/main/java/org/eclipse/edc/azure/blob/api/BlobStoreApiImpl.java#L80) makes uses of the `sharedKey` if exist, instead of trying to resolve the key again.

The behavior was reported in test addition done in by this [tractusx-edc](https://github.com/eclipse-tractusx/tractusx-edc/pull/1154) PR

**Comment by bmg13** [comment]
Can you assign this issue to me @yurimssilva please?
