### ISSUE TITLE
AzureStorageDataSinkFactory relies on Source properties

### ISSUE THREAD

**Issue by yurimssilva** [eclipse-edc/Technology-Azure#169]
# Bug Report

## Describe the Bug

During a multi object transfer process, when the `DataSource` is not `AzureStorage`, an issue arises if the `Consumer` defines a `blobName` in the destination. In this scenario, all objects are overwritten using the same file name, resulting in data loss or unintended overwriting. This occurs due to the reliance of the `AzureStorageDataSinkFactory` on `DataSource` specifics, particularly the `blobPrefix` property, which is further utilized to determine object naming, if the property is present it would mean it is a multi object transfer, but it is true only if the `DataSource` is `AzureStorage`.

`AzureStorageDataSinkFactory`:
https://github.com/eclipse-edc/Technology-Azure/blob/fdbc521750959868cf1ff6c93230e6220ba8ab70/extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSinkFactory.java#L77-L88

`AzureStorageDataSink`:
https://github.com/eclipse-edc/Technology-Azure/blob/fdbc521750959868cf1ff6c93230e6220ba8ab70/extensions/data-plane/data-plane-azure-storage/src/main/java/org/eclipse/edc/connector/dataplane/azure/storage/pipeline/AzureStorageDataSink.java#L58-L65

The behavior was reported in test addition done in by this [tractusx-edc](https://github.com/eclipse-tractusx/tractusx-edc/pull/1154) PR.

**Comment by zub4t** [comment]
Can you assign this to me? @ndr-brt  😁
