### ISSUE TITLE
Release 0.7.1 depends on edc 0.7.1-SNAPSHOT

### ISSUE THREAD

**Issue by rafaelmag110** [eclipse-edc/Technology-Azure#234]
# Bug Report

## Describe the Bug

The released version 0.7.1 depends on edc artifacts with tag 0.7.1-SNAPSHOT which no longer exist.
New builds dependent on this version break.

**Comment by paullatzelsperger** [comment]
`0.7.1-SNAPSHOT` very much exists, pls refer to the OSSRH Snapshot repos. However, this was an oversight on our part, but since it is a released version, there's nothing we can do about it. So I am not sure what the intention in raising this issue was.

**Comment by rafaelmag110** [comment]
A fix was created for version 0.7.1 and will be included in 0.7.2.
The release workflow will also be improved in main within a planned refactor.
