### ISSUE TITLE
Azure Dataplane does not register any generator function for AzureStorage type (v0.7.1)

### ISSUE THREAD

**Issue by rafaelmag110** [eclipse-edc/Technology-Azure#236]
# Bug Report

## Describe the Bug

Similar to https://github.com/eclipse-edc/Technology-Aws/issues/401 but for AzureStorage.

This issue only impacts 0.7.X. versions. 
The issue was fixed for 0.8.0 and the solution shouldn't be merged to the main branch.

**Comment by ndr-brt** [comment]
already resolved in main, was backported in 0.7.2 by #237
